default:
  #sched: onecycle
  sched: step
  opt: adam
  lr: 0.001  
  decay_epoch: 50
  decay_rate: 0.5
  warmup_lr: 0.0001
  warmup_epoch: 10
  batch_size: 16
  random_split: True 
  num_classes: 1

exp_s2:
  # as regression problem
  # small data
  decay_epoch: 50
  decay_rate: 0.5
  lr: 0.001
  warmup_lr: 0.0001
  warmup_epoch: 20
  batch_size: 16
  random_split: True
  num_classes: 1
  in_shape:
    - 12
    - 1
    - 100
    - 100